### ISSUE TITLE
Category search - Adjust criteria display

### ISSUE THREAD

**Issue by ChrSchuettler** [medizininformatik-initiative/feasibility-gui#10]
Indenting the criteria display in a way that checkboxes and the arrows of the fold-out criteria folders are on one level

**Comment by juliangruendner** [comment]
@ChrSchuettler  - please add a screenshot of the intended change

**Comment by ChrSchuettler** [comment]
![grafik](https://user-images.githubusercontent.com/48763581/183420734-9096e536-7b09-4d1a-b8c3-ede2fa8f5fbb.png)
