### ISSUE TITLE
Update saving of queries

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-gui#116]
Based on this issue from the backend, the UI should be adjusted to save and load queries with a result.
https://github.com/medizininformatik-initiative/feasibility-backend/pull/204

For all backend calls see the swagger information: <https://raw.githubusercontent.com/medizininformatik-initiative/feasibility-backend/1cf4dd42125a748ae9640618797c732bb8e1f589/src/main/resources/static/v3/api-docs/swagger.yaml>

To support the new saving of queries:

**Support saving of a query (saved query) with the result from the UI:**
It should be possible to save a query with result.
Backend call: POST /query/{queryId}/saved
content:
{
  "label": "my-query-1",
  "comment": "I wanted to see how many patients I could find for my study XYZ",
  "totalNumberOfPatients": 12345
}

Note that the backend will return a 403 (forbidden) and an appropriate feasibility error if the user has run out of slots.

**Support DELETE of a saved query:**
It should be possible to delete a saved query by clicking a "delete" button next to the query
Backend call: DELETE /query/{queryId}/saved

**Display information about saved query slots left:**
The user has only a limited number of queries he is a allowed to save at any given time.

The number can retrieved from the backend with the following call:
GET /query/saved-query-slots
and will return the following object
{
  "used": 2,
  "total": 10
}

**Comment by mgebhardttmf** [comment]
Habt ihr eine richtige Swagger-API? Der Link oben funktioniert nicht.
