### ISSUE TITLE
Save function - enable renaming

### ISSUE THREAD

**Issue by ChrSchuettler** [medizininformatik-initiative/feasibility-gui#16]
Enable renaming of a saved query

**Comment by juliangruendner** [comment]
@michael-82  - need to discuss to allow for CRUD methods on the saved queries for the backend

**Comment by michael-82** [comment]
Well, we already got the CR part covered. Delete should be trivial

```
DELETE /v2/query/template/{queryId}
```

As for the update we should discuss what should be possible to update. If it's only renaming, we could do something like

```
PATCH /v2/query/template/{queryId}

[
  { "op": "replace", "path": "/label", "value": "new label" },
  { "op": "replace", "path": "/comment", "value": "new comment" }
]
```
as in [rfc6902](https://datatracker.ietf.org/doc/html/rfc6902)

or slightly more lenient

```
PATCH /v2/query/template/{queryId}

{
  "label": "new label",
  "comment": "new comment
}
```
