### ISSUE TITLE
Criteria Search - Remove first hierarchy level

### ISSUE THREAD

**Issue by ChrSchuettler** [medizininformatik-initiative/feasibility-gui#18]
The first hierarchy level of the folder structure should be removed so that this is not redundant in the display

**Comment by juliangruendner** [comment]
@geloro94  - can you give feedback whether you need to change this in the ontology generation or @thkoehler11  has to change this in the UI

**Comment by geloro94** [comment]
I will change this in the ontology generation.

**Comment by geloro94** [comment]
Ontology generated with https://github.com/medizininformatik-initiative/fhir-ontology-generator/commit/fb2cb74d5f7221be2410ea68ab8be57eae32c194 fixes this.
