### ISSUE TITLE
Save function – Set date of "saved queries display" in German

### ISSUE THREAD

**Issue by mzerlik** [medizininformatik-initiative/feasibility-gui#24]
The date of saved queries should be displayed in German (not in English).

![gespeicherteAbfrage_datumsanzeige](https://user-images.githubusercontent.com/103411351/163604232-b72abcdf-3b54-4e59-aaee-7a56a402d44c.png)

**Comment by juliangruendner** [comment]
<img width="1277" alt="image" src="https://github.com/medizininformatik-initiative/feasibility-gui/assets/18329952/5ea1f0ab-d02b-4db4-8560-20a5308e4c55">

The date of the queries should be displayed for templates as well as saved queries.

When switching to German the date should be displayed in German format

**Comment by juliangruendner** [comment]
> Please confirm the new date format, where the month is displayed numerically instead of being written out in full. @juliangruendner
> 
> ![image](https://user-images.githubusercontent.com/102315366/255623454-d461f562-8fe1-4479-a9d8-ab507e536014.png)
> 
> **Solution** File path `/opt/feasibility-gui/src/app/modules/querybuilder/components/querybuilder-overview/single-query/single-query.component.html`. Add: ` <div class="query-box-date">{{ singleDate | date: 'dd.MM.yyyy' }}</div>`

sounds good.
