### ISSUE TITLE
Filter design incorrect

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-gui#264]
The current filter selection design for multiselects is not correct.

Change to the filter design as specified in figma:

<img width="535" alt="image" src="https://github.com/user-attachments/assets/1650e360-31fd-4160-b532-c3db7b8e3036">

**Comment by Shayan1375** [comment]
Having two buttons for setting a filter can be redundant and can overcomplicate the user interface
