### ISSUE TITLE
Display of selected criteria - Add code to display

### ISSUE THREAD

**Issue by ChrSchuettler** [medizininformatik-initiative/feasibility-gui#5]
Show code when displaying the selected criteria to be able to distinguish criteria with the same name

Implementation depending on feasibility: 
1) Option 2
2) Option 1
3) Option 3

![AnzeigeCode_ausgewaehlteMrkmale](https://user-images.githubusercontent.com/48763581/164222415-85557e94-4ec2-4573-a84b-469f33c90888.png)

**Comment by ChrSchuettler** [comment]
For longer numbers this would have to be cut off if necessary

**Comment by TimoFuchsUKR** [comment]
Same in the selection-window. The current structure is sorted by name, should be sorted by code:

(OPS-Codes for example)
(3-03...3-99) Bildgebende Diagnostik
(3-20...3-26) Computertomographie [CT]
3-20 Computertomographie [CT], nativ
3-200 Native Computertomographie des Schädels

PS: Searching for codes with many subcodes is not possible (e.g. ECMO 8-852), the officiell structure would be better.

**Comment by juliangruendner** [comment]
@kleinertp  - we should make a final decision wether we would like the code to be displayed or not
