### ISSUE TITLE
Feature request - Adding KDS based icons

### ISSUE THREAD

**Issue by geloro94** [medizininformatik-initiative/feasibility-gui#57]
When adding criteria information on the source KDS is lost. By adding KDS-based Icons this information could be retained.
Example:

![grafik](https://user-images.githubusercontent.com/24481264/189911296-a490742c-7e50-40b3-af09-5f449e869966.png)

**Comment by juliangruendner** [comment]
@kleinertp - please confirm wether this feature should be implemented
