### ISSUE TITLE
Error "Too many requests" - Spell Check

### ISSUE THREAD

**Issue by ChrSchuettler** [medizininformatik-initiative/feasibility-gui#67]
Correction of the text in "Too many requests" instead of "to many request"

![image(2)](https://user-images.githubusercontent.com/48763581/204773422-0c77f13c-ae3b-4319-b42e-5eb6b4e8636b.png)

**Comment by michael-82** [comment]
The error text is not coming from the backend. Transferred to gui.

**Comment by juliangruendner** [comment]
outdated - not relevant as superseded by new error handling
