### ISSUE TITLE
roter Kasten Update

### ISSUE THREAD

**Issue by kleinertp** [medizininformatik-initiative/feasibility-gui#85]
Bitte diesen Text in den roten Kasten auf der Startseite des Feasibilityportals:

Das hier weg:
 "Das Portal wird im Moment aktualisiert. Dies kann dazu führen, dass eine reduzierte Anzahl an Standorten Patientenzahlen zurückgibt" 

Und das hier rein:
"""
Das Portal wird laufend verbessert und erweitert. Einige Standorte haben ihre automatisiert abfragbaren Datensätze reduziert (z.b. auf Daten einzelner Jahre oder konsentierte Daten). Die tatsächliche Datenmenge und die Anzahl liefernder Standorte kann daher nach Durchlaufen des Antragsprozess (je nach Analysemethode) deutlich größer ausfallen als das Ergebnis der Machbarkeitsanalyse. Sie haben Ihre gewünschten Daten nicht gefunden? Kontaktieren Sie uns unter: [info@forschen-fuer-gesundheit.de](mailto:info@forschen-fuer-gesundheit.de)
"""

**Comment by kleinertp** [comment]
engl:

The portal is continuously improved and expanded. Some sites have reduced their automatically queryable data sets (e.g., to single year data or consented data). The actual amount of data and the number of providing sites may therefore be significantly larger than the result of the feasibility analysis after going through the application process (depending on the analysis method). You did not find your desired data? Contact us at: info@forschen-fuer-gesundheit.de

**Comment by juliangruendner** [comment]
implemented for live system
