### ISSUE TITLE
Improve Error Handling

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-gui#88]
The user should get more information on errors occurring in the UI.

This issue can only be started after the following pull request has been successfully merged:
https://github.com/medizininformatik-initiative/feasibility-backend/pull/141

All error messages / notifications should be displayed in a snackbar in the middle at the top of the screen for 10 seconds and be handled via lang files.
The snackbar should be implemented in its own template which should be adjustable later and be automatically applied to all error messages.
A first design can look as follows:

<img width="1285" alt="example-error-snackbar-1" src="https://github.com/medizininformatik-initiative/feasibility-gui/assets/18329952/97ed814a-6f94-4b04-9074-8ea5e77d61c7">

Generally error messages from the backend follow the pattern that they use the standard http status to convey the problem.
Where this is not possible extended error messages are send using the http body and include N issues, as follows (Example feasibility issue 10004):

```
{
    "issues": [
        {
            "message": "Total number of results below threshold",
            "type": "busy",
            "code": "FEAS-10004",
            "severity": "error"
        }
    ]
}
```

##The UI should handle the following Errors:

### Error: Blacklisted

In component: querybuilder-editor
Identified by:
1. HTTP status = 403
2. issue code = FEAS-10001
How to induce in local setup:
Set env var PRIVACY_QUOTA_HARD_CREATE_AMOUNT of backend to 1
Ensure your user is not a power user in your local keycloak and send at least 2 requests

Example code in UI (simple example for orientation):
```
...
(error) => {

        if ('issues' in error.error) {
          if (error.error['issues'].some(issue => issue.code === 'FEAS-10001')) {
            console.log("reached blacklisted")
            this.translate.get('QUERYBUILDER.ERROR.BLACKLISTED').subscribe((res: string) => {
              this._snackBar.open(res, "close", { duration: 10 * 1000, verticalPosition: "top" })
            });
          }
        }
      }
```

Error message to display:
DE: Ihr Benutzer wurde wegen zu vielen Anfragen gesperrt, bitte wenden Sie sich an info@forschen-fuer-gesundheit.de
EN: Your user was blacklisted because you send to many queries, please contact info@forschen-fuer-gesundheit.de

**Ensure that your user is a power user or reset ur backend DB after this test**

### Error: Too many requests - quota reached

In component: querybuilder-editor
Identified by:
1. HTTP status = 429
2. issue code = FEAS-10002
How to induce in local setup:
Set env var PRIVACY_QUOTA_SOFT_CREATE_AMOUNT of backend to 1
Send more than 1 request in 60 seconds.

Error message to display:
RETRY_AFTER should be taken from the header "Retry-After" of the error response

DE: Sie haben zu viele Anfragen gestellt, bitte warten Sie RETRY_AFTER Sekunden und probieren Sie es erneut
EN: You sent too many queries, please wait RETRY_AFTER seconds and try again

### Error: Result not large enough

In component: querybuilder-editor
Identified by:
1. HTTP status = 200
2. issue code = FEAS-10004
How to induce in local setup:
Set env var PRIVACY_THRESHOLD_RESULTS of backend to 1000000
send a request

Note: This is a special case, as we poll the results in regular intervals and the error message should only be shown
if there has been no result large enough at the end of the polling time.
One way to solve this is to set a variable that the result is not large enough during the polling 
and then in the "done" part of the subscription set the error accordingly.

Example (this is only an example - code will have to be cleaned up, lang variables introduced etc.):

```
this.subscriptionPolling = this.resultObservable$.subscribe(
      (result) => {

        if ('issues' in result) {
          if (result['issues'].some(issue => issue.code === 'FEAS-10004')) {
            this.resultsLargeEnough = false;
          }
        } else {
          this.resultsLargeEnough = true;
          this.result = result;
          if (result.queryId !== undefined) {
            this.hasQuerySend = result.queryId;
          } else {
            this.hasQuerySend = false;
          }
        }
      },
      (error) => {
        console.log(error);
        this.showSpinningIcon = false;
        this.hasQuerySend = false;
        if (error.status === 404) {
          window.alert('Site not found');
        }
      },
      () => {
        console.log('done');
        if (this.resultsLargeEnough == false) {
          this._snackBar.open("Result size not large enough - not showing results", "close", { duration: 10 * 1000, verticalPosition: "top" })
        } else {
          this.loadedResult = true;
        }

        this.showSpinningIcon = false;
      }
    );
```

Error message to display:
DE: Die Ergebnismenge ist zu klein -> Ergebnis wird nicht angezeigt
EN: The result size is too small -> result will not be shown

### Error: Not enough sites answered

In component: result-details-dialog
Identified by:
1. HTTP status = 200
2. issue code = FEAS-10005
How to induce in local setup:
Set env var PRIVACY_THRESHOLD_SITES of backend to 1000
send a request - wait for polling to end
click the details button.

Example code:
```
if ('issues' in result) {
            if (result['issues'].some(issue => issue.code === 'FEAS-10005')) {
              this._snackBar.open("Not enough sites answered", "close", { duration: 10 * 1000, verticalPosition: "top" })
            }
          }
```

Error message to display:
DE: Die Anzahl der Standorte die geantwortet haben ist zu klein -> Detailergebnis wird nicht angezeigt
EN: The number of sites which answered is too small -> detailed results are not shown

**Comment by Shayan1375** [comment]
Anbei das UI der implementierten Snackbar @juliangruendner  @mgebhardttmf @kleinertp  : 

**Die Snackbar mit der Fehlermeldung in der Detailansicht**
![Snackbar_Detailansichtl](https://github.com/medizininformatik-initiative/feasibility-gui/assets/102315366/91846cb2-99ec-48c9-9aab-addfd404cef1)

**Das zweite Bild stellt die Snackbar in der Gesamtansicht dar.**
![Snackbar_Gesamtansicht](https://github.com/medizininformatik-initiative/feasibility-gui/assets/102315366/b116ffa5-b2cd-418d-babe-80159d4d38db)

**Comment by kleinertp** [comment]
Mein Vorschlag:

"Ihr Account wurde aus Sicherheitsgründen wegen zu vielen Anfragen vorrübergehend gesperrt. Zur Entsperrung wenden Sie sich an info@forschen-fuer-gesundheit.de"

"Your account has been temporarily locked for security reasons due to too many requests. To unblock your account, please contact info@forschen-fuer-gesundheit.de."
