### ISSUE TITLE
Adjust UI to Support Ontology 2.0

### ISSUE THREAD

**Issue by juliangruendner** [medizininformatik-initiative/feasibility-gui#95]
With ontology 2.0 the ui_profiles are extend with a **context** and the ui_profile details are no longer available when the backend endpoint entries/{nodeId} is called. Instead it **only returns the ui-tree without additional ui_profile** information such as the attribute or value definitions.

Example excerpt of the ui-tree for specimen
```
{
                    "context": {
                        "code": "Specimen",
                        "display": "Bioprobe",
                        "system": "fdpg.mii.cds",
                        "version": "1.0.0"
                    },
                    "display": "a.m. serum specimen",
                    "id": "7fd85c7a-577a-3adc-ede1-169fb82b7032",
                    "leaf": true,
                    "selectable": true,
                    "termCodes": [
                        {
                            "code": "442166002",
                            "display": "a.m. serum specimen",
                            "system": "http://snomed.info/sct",
                            "version": "http://snomed.info/sct/900000000000207008/version/20230430"
                        }
                    ]
                }
```

This means that additional information such as attributeDefinitions are not part of the tree anymore and there is an additional context which has to be considered.

### 1. Add Context to internal data models

When reading the ui tree the context has to be added to the internal TerminologyEntry class
Note: Context has the same properties as the TerminologyCode class

Further double check that the fact that the ui_profile properties missing in the return value of entries/{nodeId}
does not destroy the building of the ui-tree in the UI.

### 2. Use Context when "Adding" or "Editing a criterion

When "Adding" or "Editing a criterion to load the appropriate ui_profile for it, a call to the backend endpoint: ui_profile has to be made.
This endpoint now expects not only the termcode but also the context information as follows:

```
ui_profile?system=<termcode-system-here>&code=<termcode-code-here>&version=<termcode-version-here>&context_system=<context-system-here>&context_code=<context-code-here>&context_version=<context-version-here>
```

Note: version in both cases is not a required parameter, but should be used if available.

### 3. Add Context to SQ - configurable via feature toggle

The Context information should be added to the SQ alongside the termcode for each criterion.
Therefore a Context should be added to the Criterion class.

Whether the context information is then sent to the backend or not should be configurable via a feature toggle in the config of the UI. 

**Hint:** One class that could potentially be extended to make this configurable is the ApiTranslator.

**Comment by Shayan1375** [comment]
Please note: The recent commit medizininformatik-initiative/feasibility-backend@2fbb207 introduced changes to the backend endpoints. Consequently, the frontend paths have been adjusted in commit 4461c55 to align with the updates.
